# Generated by Django 6.1 on 2026-08-13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_system_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="Initiative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("title", models.CharField(max_length=200)),
                ("summary", models.TextField(blank=True)),
                ("body_html", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposal", "Proposal"),
                            ("seeking-contributors", "Seeking contributors"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                        ],
                        default="active",
                        max_length=30,
                    ),
                ),
                ("loomio_url", models.URLField(blank=True)),
                ("matrix_room", models.CharField(blank=True, max_length=200)),
                ("updates", models.JSONField(blank=True, default=list)),
                (
                    "systems",
                    models.ManyToManyField(
                        blank=True, related_name="initiatives", to="pages.system"
                    ),
                ),
                (
                    "takers",
                    models.ManyToManyField(
                        blank=True, related_name="initiatives_led", to="pages.member"
                    ),
                ),
            ],
            options={
                "ordering": ["slug"],
            },
        ),
        migrations.AddField(
            model_name="article",
            name="initiative",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="articles",
                to="pages.initiative",
            ),
        ),
    ]
