# Generated by Django 6.1 on 2026-08-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0004_initiative"),
    ]

    operations = [
        migrations.AddField(
            model_name="initiative",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="initiative",
            name="start_date",
            field=models.DateField(default="2026-01-01"),
            preserve_default=False,
        ),
    ]
