# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0006_lifecycle_recruiting"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="matrix_room",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="group",
            name="summary",
            field=models.TextField(blank=True),
        ),
    ]
