# Generated by Django 6.1 on 2026-08-08 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('body_html', models.TextField()),
                ('updates', models.JSONField(blank=True, default=list)),
                ('admins', models.ManyToManyField(blank=True, related_name='systems_administered', to='pages.member')),
                ('teamlead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='systems_led', to='pages.member')),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('title', models.CharField(max_length=500)),
                ('state', models.CharField(max_length=10)),
                ('url', models.URLField(max_length=500)),
                ('labels', models.JSONField(blank=True, default=list)),
                ('author', models.CharField(max_length=200)),
                ('is_pull', models.BooleanField(default=False)),
                ('merged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='pages.system')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
