# Generated by Django 6.1 on 2026-08-06 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('tags', models.JSONField(blank=True, default=list)),
                ('summary', models.TextField(blank=True)),
                ('body_html', models.TextField()),
            ],
            options={
                'ordering': ['-date', 'slug'],
            },
        ),
    ]
